package runtime

import (
	"fmt"
	"time"

	"github.com/castwell/forge/internal/forgex/model"
	forgestorage "github.com/castwell/forge/internal/storage"
)

func renderReport(runID, workflowID string, status model.RunStatus, startedAt, endedAt time.Time, terminalEvent forgestorage.EventType) string {
	duration := endedAt.Sub(startedAt)
	return fmt.Sprintf(`# ForgeX Runtime Observer Report

## Summary

- Run ID: %s
- Source: Forge Runtime
- Forge Workflow ID: %s
- Status: %s
- Terminal Event: %s
- Started At: %s
- Ended At: %s
- Duration: %s

## Scope

This report was generated by the ForgeX runtime observer. The observer is currently **observe-only**: it records Forge workflow/task events into ForgeX artifacts but does not change Forge scheduling, retry, compensation, or worker execution semantics.

## Artifacts

- run.json
- task_packet.yaml
- events.jsonl
- report.md
`, runID, workflowID, status, terminalEvent, startedAt.Format(time.RFC3339), endedAt.Format(time.RFC3339), duration)
}

func reportGeneratedEvent(runID, workflowID string, terminalEvent forgestorage.EventType, timestamp time.Time) model.Event {
	return model.Event{
		ID:        fmt.Sprintf("forge_report_%d", timestamp.UnixNano()),
		RunID:     runID,
		Type:      model.EventReportGenerated,
		Message:   "forge runtime observer report generated",
		Timestamp: timestamp,
		Data: map[string]any{
			"source":            "forge_runtime",
			"forge_workflow_id": workflowID,
			"terminal_event":    string(terminalEvent),
		},
	}
}
