import type {
  OverviewData,
  WorkflowInstance,
  WorkflowListData,
  WorkerInfo,
  WorkerListData,
} from './types';

const mockWorkflows: WorkflowInstance[] = [
  {
    id: 'wf-001',
    name: 'data-pipeline',
    version: 1,
    status: 'WORKFLOW_STATUS_COMPLETED',
    input: '{}',
    output: '{"result": "ok"}',
    errorMsg: '',
    tasks: [
      {
        id: 'task-001',
        taskName: 'extract',
        handler: 'extract_handler',
        status: 'TASK_STATUS_COMPLETED',
        workerId: 'worker-go-1',
        input: '{}',
        output: '{}',
        errorMsg: '',
        attempt: 1,
        maxAttempts: 3,
        scheduledAt: '2026-04-22T08:00:00Z',
        startedAt: '2026-04-22T08:00:01Z',
        finishedAt: '2026-04-22T08:00:10Z',
        createdAt: '2026-04-22T08:00:00Z',
        dependsOn: [],
      },
      {
        id: 'task-002',
        taskName: 'transform',
        handler: 'transform_handler',
        status: 'TASK_STATUS_COMPLETED',
        workerId: 'worker-py-1',
        input: '{}',
        output: '{}',
        errorMsg: '',
        attempt: 1,
        maxAttempts: 3,
        scheduledAt: '2026-04-22T08:00:10Z',
        startedAt: '2026-04-22T08:00:11Z',
        finishedAt: '2026-04-22T08:00:30Z',
        createdAt: '2026-04-22T08:00:00Z',
        dependsOn: ['extract'],
      },
      {
        id: 'task-003',
        taskName: 'validate',
        handler: 'validate_handler',
        status: 'TASK_STATUS_COMPLETED',
        workerId: 'worker-go-1',
        input: '{}',
        output: '{}',
        errorMsg: '',
        attempt: 1,
        maxAttempts: 3,
        scheduledAt: '2026-04-22T08:00:10Z',
        startedAt: '2026-04-22T08:00:12Z',
        finishedAt: '2026-04-22T08:00:25Z',
        createdAt: '2026-04-22T08:00:00Z',
        dependsOn: ['extract'],
      },
      {
        id: 'task-004',
        taskName: 'load',
        handler: 'load_handler',
        status: 'TASK_STATUS_COMPLETED',
        workerId: 'worker-go-2',
        input: '{}',
        output: '{}',
        errorMsg: '',
        attempt: 1,
        maxAttempts: 3,
        scheduledAt: '2026-04-22T08:00:30Z',
        startedAt: '2026-04-22T08:00:31Z',
        finishedAt: '2026-04-22T08:00:45Z',
        createdAt: '2026-04-22T08:00:00Z',
        dependsOn: ['transform', 'validate'],
      },
      {
        id: 'task-005',
        taskName: 'notify',
        handler: 'notify_handler',
        status: 'TASK_STATUS_COMPLETED',
        workerId: 'worker-py-1',
        input: '{}',
        output: '{}',
        errorMsg: '',
        attempt: 1,
        maxAttempts: 3,
        scheduledAt: '2026-04-22T08:00:45Z',
        startedAt: '2026-04-22T08:00:46Z',
        finishedAt: '2026-04-22T08:00:50Z',
        createdAt: '2026-04-22T08:00:00Z',
        dependsOn: ['load'],
      },
    ],
    startedAt: '2026-04-22T08:00:00Z',
    finishedAt: '2026-04-22T08:00:50Z',
    createdAt: '2026-04-22T07:59:55Z',
  },
  {
    id: 'wf-002',
    name: 'ml-training',
    version: 1,
    status: 'WORKFLOW_STATUS_RUNNING',
    input: '{"model": "gpt"}',
    output: '',
    errorMsg: '',
    tasks: [
      {
        id: 'task-006',
        taskName: 'preprocess',
        handler: 'preprocess_handler',
        status: 'TASK_STATUS_COMPLETED',
        workerId: 'worker-py-1',
        input: '{}',
        output: '{}',
        errorMsg: '',
        attempt: 1,
        maxAttempts: 3,
        scheduledAt: '2026-04-22T09:00:00Z',
        startedAt: '2026-04-22T09:00:01Z',
        finishedAt: '2026-04-22T09:01:00Z',
        createdAt: '2026-04-22T09:00:00Z',
        dependsOn: [],
      },
      {
        id: 'task-007',
        taskName: 'train',
        handler: 'train_handler',
        status: 'TASK_STATUS_RUNNING',
        workerId: 'worker-cpp-1',
        input: '{}',
        output: '',
        errorMsg: '',
        attempt: 1,
        maxAttempts: 3,
        scheduledAt: '2026-04-22T09:01:00Z',
        startedAt: '2026-04-22T09:01:01Z',
        finishedAt: '',
        createdAt: '2026-04-22T09:00:00Z',
        dependsOn: ['preprocess'],
      },
      {
        id: 'task-008',
        taskName: 'evaluate',
        handler: 'evaluate_handler',
        status: 'TASK_STATUS_PENDING',
        workerId: '',
        input: '{}',
        output: '',
        errorMsg: '',
        attempt: 0,
        maxAttempts: 3,
        scheduledAt: '',
        startedAt: '',
        finishedAt: '',
        createdAt: '2026-04-22T09:00:00Z',
        dependsOn: ['train'],
      },
    ],
    startedAt: '2026-04-22T09:00:00Z',
    finishedAt: '',
    createdAt: '2026-04-22T08:59:50Z',
  },
  {
    id: 'wf-003',
    name: 'deploy-service',
    version: 2,
    status: 'WORKFLOW_STATUS_FAILED',
    input: '{"env": "prod"}',
    output: '',
    errorMsg: 'health check failed',
    tasks: [
      {
        id: 'task-009',
        taskName: 'build',
        handler: 'build_handler',
        status: 'TASK_STATUS_COMPLETED',
        workerId: 'worker-go-1',
        input: '{}',
        output: '{}',
        errorMsg: '',
        attempt: 1,
        maxAttempts: 3,
        scheduledAt: '2026-04-22T10:00:00Z',
        startedAt: '2026-04-22T10:00:01Z',
        finishedAt: '2026-04-22T10:02:00Z',
        createdAt: '2026-04-22T10:00:00Z',
        dependsOn: [],
      },
      {
        id: 'task-010',
        taskName: 'deploy',
        handler: 'deploy_handler',
        status: 'TASK_STATUS_FAILED',
        workerId: 'worker-go-2',
        input: '{}',
        output: '',
        errorMsg: 'health check failed after 3 attempts',
        attempt: 3,
        maxAttempts: 3,
        scheduledAt: '2026-04-22T10:02:00Z',
        startedAt: '2026-04-22T10:02:01Z',
        finishedAt: '2026-04-22T10:05:00Z',
        createdAt: '2026-04-22T10:00:00Z',
        dependsOn: ['build'],
      },
      {
        id: 'task-011',
        taskName: 'rollback',
        handler: 'rollback_handler',
        status: 'TASK_STATUS_SKIPPED',
        workerId: '',
        input: '{}',
        output: '',
        errorMsg: '',
        attempt: 0,
        maxAttempts: 1,
        scheduledAt: '',
        startedAt: '',
        finishedAt: '',
        createdAt: '2026-04-22T10:00:00Z',
        dependsOn: ['deploy'],
      },
    ],
    startedAt: '2026-04-22T10:00:00Z',
    finishedAt: '2026-04-22T10:05:00Z',
    createdAt: '2026-04-22T09:59:50Z',
  },
];

const mockWorkers: WorkerInfo[] = [
  {
    id: 'worker-go-1',
    addr: '10.0.1.10:9000',
    labels: { language: 'go', region: 'us-east-1' },
    capacity: 10,
    activeTasks: 3,
    status: 'healthy',
    handlers: ['extract_handler', 'validate_handler', 'build_handler'],
  },
  {
    id: 'worker-go-2',
    addr: '10.0.1.11:9000',
    labels: { language: 'go', region: 'us-east-1' },
    capacity: 10,
    activeTasks: 1,
    status: 'healthy',
    handlers: ['load_handler', 'deploy_handler'],
  },
  {
    id: 'worker-py-1',
    addr: '10.0.2.10:9000',
    labels: { language: 'python', gpu: 'true' },
    capacity: 5,
    activeTasks: 2,
    status: 'healthy',
    handlers: ['preprocess_handler', 'transform_handler', 'notify_handler', 'evaluate_handler'],
  },
  {
    id: 'worker-cpp-1',
    addr: '10.0.3.10:9000',
    labels: { language: 'cpp', gpu: 'true' },
    capacity: 4,
    activeTasks: 1,
    status: 'unhealthy',
    handlers: ['train_handler'],
  },
];

const mockOverview: OverviewData = {
  activeWorkflows: 1,
  totalWorkflows: 3,
  totalWorkers: 4,
  healthyWorkers: 3,
  successRate: 0.5,
  queueDepth: 1,
  failedWorkflows: 1,
};

export function getMockOverview(): OverviewData {
  return mockOverview;
}

export function getMockWorkflows(): WorkflowListData {
  return { workflows: mockWorkflows, nextPageToken: '' };
}

export function getMockWorkflow(id: string): WorkflowInstance | undefined {
  return mockWorkflows.find((wf) => wf.id === id);
}

export function getMockWorkers(): WorkerListData {
  return { workers: mockWorkers, nextPageToken: '' };
}
